[RUN]
seed = 7
episodes = 5000
max_steps = 1000
evaluation_episodes = 20
save_dir = "model"
save_frames = false
visualization_path = "videos"
log_dir = "logs"
title = "Lunar-lander-DoubleDQN-Power19.0-0.4"

[AGENT]
device = "cpu"
recurrent = false
network_hidden_layers = [128, 64]
lr = 0.0001
lr_decay = 1.0
replay_buffer_size = 50000
batch_size = 64
gamma = 0.99
steps_before_learning = 500
clip_grad = 1.0
tau = 0.001
network_update_freq = 5
n_epochs = 1
epsilon_initial = 1.0
epsilon_final = 0.01
epsilon_decay = 0.995

[ENVIRONMENT]
gravity = -10.0
enable_wind = false
wind_power = 15.0
turbulence_power = 1.5
main_engine_power = 19.0
side_engine_power = 0.4
wrapper_class = "none"
wrapper_scale = [1.0]
wrapper_noise_level = [0.001]
wrapper_scale_test = [0.0]
wrapper_noise_level_test = [0.0]
